apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: streamlit
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 8501 #Service port
    targetPort: 8501 #The port for the React.js application container
